# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# B121-tables.py
# Created on: 2021-09-29 19:25:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
tables = "E:\\00_Cloud\\Surfdrive\\Shared\\URC-Daniele\\01_indicators\\B.1.2.1a\\output\\viewshed\\tables"
Name = "rs09"
Table = "E:\\00_Cloud\\Surfdrive\\Shared\\URC-Daniele\\01_indicators\\B.1.2.1a\\output\\viewshed\\tables\\rs09.dbf"
v_Name__visibility_dbf = "E:\\00_Cloud\\Surfdrive\\Shared\\URC-Daniele\\01_indicators\\B.1.2.1a\\output\\viewshed\\tables_sum\\%Name%_visibility.dbf"
v_Name__totale_dbf = "E:\\00_Cloud\\Surfdrive\\Shared\\URC-Daniele\\01_indicators\\B.1.2.1a\\output\\viewshed\\tables_sum\\%Name%_totale.dbf"

# Process: Iterate Tables
arcpy.IterateTables_mb(tables, "", "", "NOT_RECURSIVE")

# Process: Summary Statistics
arcpy.Statistics_analysis(Table, v_Name__visibility_dbf, "COUNT SUM;segment FIRST", "visibility")

# Process: Summary Statistics (2)
arcpy.Statistics_analysis(Table, v_Name__totale_dbf, "COUNT SUM", "segment")

